version: "3.9"

services:
  # web:
  #   build: ./front
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  # web-tests:
  #   image: bachelor_web
  #   volumes:
  #     - ./front:/app
  #   command: npm test
  api:
    build: ./back
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/bachelor
    volumes:
      - ./back:/app
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - bachelor:/data/db

volumes:
  bachelor:
