version: "3.9"

services:
  # web:
  #   build: ./front/uploadproject
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./front/uploadproject:/app
  api:
    build: ./back
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/bachelor
      JWT_SECRET: thisismynewcourse
      PORT: 3000
      # PASS: 
    volumes:
      - ./back:/app
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - bachelor:/data/db

volumes:
  bachelor:
